#!/bin/bash

# Check if we are inside a git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "This is not a git repository!"
    exit 1
fi

# Display the file tree of the current repository
git ls-tree --full-name --name-only -t -r HEAD | \
sed -e 's/[^-][^/]*//   |/g' \
    -e 's/|([^ ])/|-- \1/'
